inherit_gem:
  rubocop-mdsol: rubocop.yml

AllCops:
  Exclude:
    - "*gemspec"
  # NOTE: Excludes vendor from linting. Needed by GitHub Actions.
  # - https://github.com/rubocop/rubocop/issues/9832#issuecomment-873398952
  #
    - "vendor/bundle/**/*"

Metrics/ParameterLists:
  CountKeywordArgs: false

# TODO: add "EnforcedStyle: allow_single_line" once all rubys are > 3.0 to autocorrect all single-line methods to endless
# https://github.com/rubocop/rubocop/blob/20990ed3831589c0d9f202107b1b580ead8ef2c5/lib/rubocop/cop/style/single_line_methods.rb#L11
#
Style/SingleLineMethods:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
