language: ruby
cache: bundler

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

before_install:
  - gem install rubygems-update -v 2.7.8
  - gem install bundler -v 1.17.3
  - bundle --version

script: bundle exec rspec
