# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
        rails: ['5.2.8', '6.0.6', '6.1.7', '7.0.8', '7.1.4', '7.2.1']
        include:
          - rails: '4.0.13'
            ruby: '2.7'
          - rails: '4.1.16'
            ruby: '2.7'
          - rails: '4.2.11'
            ruby: '2.7'
          - rails: '5.0.7'
            ruby: '2.7'
          - rails: '5.1.7'
            ruby: '2.7'
        exclude:
          - rails: '7.2.1'
            ruby: '2.7'
          - rails: '7.2.1'
            ruby: '3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        cache-version: rails-${{ matrix.rails }} # for the cache key
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
    - name: Run benchmark
      run: bundle exec rake benchmark

    env:
      RAILS_VER: ${{ matrix.rails }}
